name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
        - os: ubuntu-22.04
          set_compiler: -DCMAKE_CXX_COMPILER=g++-12

        - os: ubuntu-22.04
          set_compiler: -DCMAKE_CXX_COMPILER=clang++-14

        - os: windows-latest

        - os: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install compilers
      if: matrix.set_compiler == '-DCMAKE_CXX_COMPILER=g++-12'
      run: |
        sudo apt install gcc-12 g++-12

    - name: Configure CMake
      run: cmake CMakeLists.txt -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -Dcrhandle_build_tests=ON ${{ matrix.set_compiler }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure -C ${{env.BUILD_TYPE}}
